title: "Clément Chevauchey - Engineering Portfolio"
description: Power Systems, Automation & Electronics
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
baseurl: '/academic-portfolio'
url: 'https://chevaucheyclement.github.io'
repo_url_base: "https://github.com/ChevaucheyClement/academic-portfolio/tree/main"
