header_pages:
  - about.md
  - projects.md
  - cv.md
  - contact.md
title: "Cl\xE9ment Chevauchey - Engineering Portfolio"
description: Power Systems, Automation & Electronics
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
baseurl: '/academic-portfolio'
url: 'https://yoficlemy.github.io'
repo_url_base: "https://github.com/YofiClemy/academic-portfolio/tree/main"
